language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "iojs"
before_script:
  - npm install -g grunt-cli
script: grunt test
addons:
    code_climate:
        repo_token: 55d134419444a71f8a409bfe7e0fe1c2cfcce91260612924a1fe731dfa577a0e
