language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
before_script:
  - npm install -g grunt-cli
script: grunt test
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
    code_climate:
        repo_token: 55d134419444a71f8a409bfe7e0fe1c2cfcce91260612924a1fe731dfa577a0e
